### ISSUE TITLE
Clerics Save Proficiencies

### ISSUE THREAD

**Issue by ghost** [ceryliae/DnDAppFiles#105]
Currently showing as Dex/Cha but is supposed to be Wis/Cha, for every cleric class domain

**Comment by afluffygrue** [comment]
You're referring only to the text under the Level 1 Feature called "Proficiencies" correct? It should be importing with the actual correct saving throw, just the text block in the feature is incorrect.

**Comment by afluffygrue** [comment]
Changed the Text block to reflect the correct saving throws. Actual saving throw tag is still correct so app function is unimpeded. Ceryliae will need to push new XML to Dropbox.
