### ISSUE TITLE
Subclass class file update to do list

### ISSUE THREAD

**Issue by ceryliae** [ceryliae/DnDAppFiles#109]
# Stuff to be added to the new class file
## Barbarian
- [x] Proficiencies
- [x] Skills
- [x] Starting Equipment
- [x] Ability Score increases at appropriate levels
- [x] Rage Damage increases at appropriate levels
- [x] Number of rages increase at appropriate levels
## Bard
- [x] Proficiencies
- [x] Skills
- [x] Starting Equipment
- [x] Ability Score increases at appropriate levels
- [x] Bardic Inspiration Dice increases at appropriate levels
- [x] Song of rest improvements at appropriate levels
## Cleric
- [x] Proficiencies
- [x] Skills
- [x] Starting Equipment
- [x] Ability Score increases at appropriate levels
## Druid
- [x] Proficiencies
- [x] Skills
- [x] Starting Equipment
- [x] Ability Score increases at appropriate levels
## Fighter
- [x] Proficiencies
- [x] Skills
- [x] Starting Equipment
- [x] Ability Score increases at appropriate levels
- [x] Add mariner fighting style
- [x] Battlemaster spells
## Monk
- [x] Proficiencies
- [x] Skills
- [x] Starting Equipment
- [x] Ability Score increases at appropriate levels
- [x] Monk ability spells
## Paladin
- [x] Proficiencies
- [x] Skills
- [x] Starting Equipment
- [x] Ability Score increases at appropriate levels
- [x] Add mariner fighting style
## Ranger
- [x] Proficiencies
- [x] Skills
- [x] Starting Equipment
- [x] Ability Score increases at appropriate levels
- [x] Create a separate class for spell-less ranger from unearthed arcana. (Wait until ranger is complete, then copy and make changes as necessary)
## Rogue
- [x] Proficiencies
- [x] Skills
- [x] Starting Equipment
- [x] Ability Score increases at appropriate levels
- [x] Swashbuckler subclass
## Sorcerer
- [x] Proficiencies
- [x] Skills
- [x] Starting Equipment
- [x] Ability Score increases at appropriate levels
- [x] Favored soul subclass
- [x] Storm subclass
- [x] Metamagic where appropriate
## Warlock
- [x] Proficiencies
- [x] Skills
- [x] Starting Equipment
- [x] Ability Score increases at appropriate levels
- [ ] Eldritch Invocations where appropriate
## Wizard
- [x] Proficiencies
- [x] Skills
- [x] Starting Equipment
- [x] Ability Score increases at appropriate levels
- [x] Artificer subclass

**Comment by JElmore** [comment]
Fight Club 5 allows you to pick spells from other classes. Is there any reason to have a separate Fighter (Eldritch Knight) class tag for spells when they get to pick from the Wizard spell list?

**Comment by ceryliae** [comment]
For the majority of the spells the eldritch knight gets to pick, they are limited to a couple schools of magic, not the entirety of the wizard spell list. The Fighter (Eldritch Knight) spell list contains only those spells. We did the same thing for the Arcane Trickster, which again, is limited in the Wizard spells they can choose.
