### ISSUE TITLE
Bestiary To Do List

### ISSUE THREAD

**Issue by ceryliae** [ceryliae/DnDAppFiles#11]
## Things to add to the Bestiary File

**Mines of Phandelver**
- [x]  Evil mage (57)
- [x]  Mormesk the Wraith (59)
- [x]  Nezzanar the Black Spider (59)
- [x]  Redbrand Ruffian (61)
- [x]  Sildar Hallwinter (61)

**Hoard of the Dragon Queen**
- [x]  Ambush Drake (88)
- [x]  Azbara Jos (88)
- [x]  Blagothkus (89)
- [x]  Captain Othelstan (89)
- [x]  Dragonclaw (89)
- [x]  Dralmorrer Borngray (90)
- [x]  Frulam Mondath (90)
- [x]  Guard Drake (91)
- [x]  Jamna Gleamsilver (91)
- [x]  Langdedrisi Cyanwrath (91)
- [x]  Pharblex Spattergoo (91)
- [x]  Rath Modar (92)
- [x]  Rezmir (93)
- [x]  Tails the White (93)

**Rise of Tiamat**
- [x]  Dragonclaw (89)
- [x]  Dragonfang (89)
- [x]  Dragonsoul (89)
- [x]  Dragonwing (90)
- [x]  Guard Drake (90)
- [x]  Ice Toad (90)
- [x]  Naergoth Bladelord (90)
- [x]  Neronvain (91)
- [x]  Rath Modar (91)
- [x]  Severin (92)
- [x]  Tiamat (92)

**Princes of the Apocalypse**
- [x] Howling Hatred Initiate
- [x] Crushing Wave Reaver
- [x] Sacred Stone Monk
- [x] Feathergale Knight
- [x] Crushing Wave Priest
- [x] Black Earth Guard
- [x] Eternal Flame Guardian
- [x] Fathomer
- [x] Howling Hatred Priest
- [x] Hurricane
- [x] Oreioth
- [x] Black Earth Priest
- [x] Dark Tide Knight
- [x] Eternal Flame Priest
- [x] One-eyed Shiver
- [x] Skyweaver
- [x] Thuri Merosska
- [x] Wiggan Nettlebee
- [x] Windharrow
- [x] Burrowshark
- [x] Grumink the Renegade
- [x] Shoalar Quanderil
- [x] Stonemelder
- [x] Elizar Dryflagon
- [x] Ghald
- [x] Hellenrae
- [x] Razerblast
- [x] Flamewrath
- [x] Miraj Vizann
- [x] Aerisi Kalinoth
- [x] Drannin Splithelm
- [x] Elemental Myrmidon
- [x] Bastian Thermandar
- [x] Marlos Urnrayle
- [x] Gar Shatterkeel
- [x] Vanifer
- [x] Olhydra
- [x] Yan-C-Bin
- [x] Imix
- [x] Ogremoch
## Things to change:

**Damage Rolls**
Damage rolls need to be added to features that don't have attack rolls, such as sneak attack. This needs to be added to nearly everything.

**Comment by ttbakiatwoam** [comment]
I am moving the dragonwing to the HotDQ because it's listed as a note I will also include it in RoT. I will get the full listing from the RoT.

**Comment by LoreMasterRoth** [comment]
Working on the RoT bestiary.

**Comment by ttbakiatwoam** [comment]
Will you check of the RoT and if you need I can list the PoA Monsters

**Comment by ceryliae** [comment]
Please do, and I will.

**Comment by ttbakiatwoam** [comment]
Howling Hatred Initiate
Crushing Wave Reaver
Sacred Stone Monk
Feathergale Knight
Crushing Wave Priest
Black Earth Guard
Eternal Flame Guardian
Fathomer
Howling Hatred Priest
Hurricane
Oreioth
Black Earth Priest
Dark Tide Knight
Eternal Flame Priest
One-eyed Shiver
Skyweaver
Thuri Merosska
Wiggan Nettlebee
Windharrow
Burrowshark
Grumink the Renegade
Shoalar Quanderil
Stonemelder
Elizar Dryflagon
Ghald
Hellenrae
Razerblast
Flamewrath
Miraj Vizann
Aerisi Kalinoth
Drannin Splithelm
Elemental Myrmidon
Bastian Thermandar
Marlos Urnrayle
Gar Shatterkeel
Vanifer
Olhydra
Yan-C-Bin
Imix
Ogremoch

There may be some typos/auto corrects
