### ISSUE TITLE
Magic Items To Do List

### ISSUE THREAD

**Issue by ceryliae** [ceryliae/DnDAppFiles#12]
## Things to add:

**Mines of Phandelver**
- [x]  Spider Staff (53)
- [x]  Staff of Defense (53)

**Hoard of the Dragon Queen**
- [x]  Black Dragon Mask (94)
- [x]  Hazirawn (94)
- [x]  Insignia of Claws (94)
- [x]  Wand of Winter (94)

**Rise of Tiamat**
- [x]  Draakhorn (93)
- [x]  Dragontooth Dagger (93)

**Rise of Tiamat PDF Supplement**
- [x]  Black Dragon Mask (4)
- [x]  Blue Dragon Mask (4)
- [x]  Red Dragon Mask (4)
- [x]  White Dragon Mask (4)

**Princes of the Apocalypse**
- [x] Balloon Pack
- [x] Bottled Breath
- [x] Claws of the Umber Hulk
- [x] Devastation Orb
- [x] Seeker Dart
- [x] Storm Boomerang
- [x] Weird Tank
- [x] Wingwear
- [x] Lost Crown of Besilmer
- [x] Orcsplitter
- [x] Drown
- [x] Ironfang
- [x] Tinderstrike
- [x] Windvane

**Comment by LoreMasterRoth** [comment]
Mask of the Dragon Queen wasn't included. I've added it in my forked file.

**Comment by ceryliae** [comment]
You'll need to submit a pull request

**Comment by LoreMasterRoth** [comment]
Done. Also the HotDQ items were already done when I began.

**Comment by ceryliae** [comment]
I never got your pull request, you sure you sent one?

**Comment by LoreMasterRoth** [comment]
I'm new to GitHub, do I assign it to you?  I'm coding the Dragon masks now.

**Comment by ceryliae** [comment]
Are you using the Mac/PC app?

**Comment by LoreMasterRoth** [comment]
I'm currently working out of the chrome browser.

**Comment by ceryliae** [comment]
Okay, what you need to do is go to the top right and click where it says fork, and then make any changes you want to make to a file, and then there should be an option to submit a pull request.

Whenever you decide to work on adding something new make sure your fork is up to date.

**Comment by LoreMasterRoth** [comment]
I'm not sure if I did it right. Bear with me. The master file now includes the new info I added.

**Comment by ceryliae** [comment]
Okay, now you need to create the pull. Try this link:
https://github.com/ceryliae/DnDAppFiles/compare

**Comment by LoreMasterRoth** [comment]
It looks like I collapsed it before comparing. I think I just directly updated the master and erased the fork. Take a look at the file. The last entry now should be the Dragontooth Dagger.

**Comment by LoreMasterRoth** [comment]
I'll not make that mistake again... hopefully.

**Comment by ceryliae** [comment]
I never got a pull request from you

**Comment by LoreMasterRoth** [comment]
Apparently it can be done without submitting one. I don't know what to say. I'm not really sure what order of operations I used. 

I'm really just trying to help. I'll do it right next time.

**Comment by ceryliae** [comment]
Alright, don't worry about it. You just forgot to make the pull request,
you did everything else okay.

**Comment by LoreMasterRoth** [comment]
Ok, this is where I got stuck last time. I have the file in my forked directory. How do I find it in the Compare changes?

**Comment by ttbakiatwoam** [comment]
I can list the PoA items if need be.

**Comment by ceryliae** [comment]
Please do
