### ISSUE TITLE
Class To Do List

### ISSUE THREAD

**Issue by ceryliae** [ceryliae/DnDAppFiles#13]
### Barbarian
- [x]   Berserker
- [x]  Totem Warrior
### Bard
- [x]  Lore
- [x]  Valor
### Cleric
- [x]  Knowledge
- [x]  Life
- [x]  Light
- [x]  Nature
- [x]  Tempest
- [x]  Trickery
- [x]  War
- [x]   Death (DMG)
### Druid
- [x]  Land
- [x]  Moon
### Fighter
- [x]  Champion 
- [x]  Battlemaster
- [x]  Eldritch Knight
### Monk
- [x]  Open Hand
- [x]  Shadow
- [x]  Four Elements
### Paladin
- [x]  Devotion
- [x]  Ancients
- [x]  Fallen (DMG)
### Ranger
- [x]  Hunter
- [x]  Beastmaster
### Rogue
- [x]  Arcane Trickster
- [x]  Thief
- [x]  Assassin
### Sorcerer
- [x]  Wild Magic
- [x]  Dragon Magic
### Warlock
- [x]  Archfey
- [x]  Fiend
- [x]  Great Old One
### Wizard
- [x]  Abjuration  
- [x]  Conjuration
- [x]  Divination  
- [x]  Enchantment  
- [x]  Evocation  
- [x]  Illusion  
- [x]  Necromancy  
- [x]  Artificer (Unearthed Arcana: Eberron)

**Comment by jp1971** [comment]
@ceryliae First off, thanks again for all of your work on this. , Second, quick note, you can easily create checkboxes in Github Issues using the following syntax `- [ ]`. They end up looking like this:
- [x] Task 1
- [ ] Task 2
- [ ] Etc.

**Comment by ceryliae** [comment]
That is awesome. Thanks.

**Comment by LoreMasterRoth** [comment]
Looks like this is done!

**Comment by ceryliae** [comment]
Only basic versions of the sorcerer and warlock versions are done. I will be finishing up a better version of sorcerer today and I don't know when I'm going to have time to make a better version of warlock

**Comment by ttbakiatwoam** [comment]
I will help work on them when I am done with the adventure books

**Comment by ttbakiatwoam** [comment]
Should this really be closed? I checked the classes file in the repo and the Monk is missing is it possible we overwrote it at some point?

**Comment by ceryliae** [comment]
I am actually looking into that right now, someone reported that to me. I had it in there, I don't know how it went missing.

**Comment by ceryliae** [comment]
Classes 1.7 is up with the monk in it.
