### ISSUE TITLE
Unable to Import Character into GM5

### ISSUE THREAD

**Issue by velowebb** [ceryliae/DnDAppFiles#135]
Sorry for the inline text, but the xml below does not import. 

<?xml version="1.0" encoding="UTF-8"?>
<characters version="5">
    <pc>
        <label>Felnot</label>
        <name>Elf (High) Ranger 3</name>
        <size>M</size>
        <ac>16 (Hide Armor)</ac>
        <hp>23/23 (3d10)</hp>
        <speed>30 ft.</speed>
        <str>12</str><dex>17</dex><con>10</con><int>10</int><wis>11</wis><cha>10</cha>
        <save>Strength +3</save>
        <save>Dexterity +5</save>
        <skill>Acrobatics +5</skill>
        <skill>Athletics +3</skill>
        <skill>Insight +2</skill>
        <skill>Intimidation +2</skill>
        <skill>Perception +2</skill>
        <skill>Stealth +5</skill>
        <passive>12</passive>
        <languages>You can speak, read, and write Common, Elvish, and one extra language of your choice. Elvish is fluid, with subtle intonations and intricate grammar. Elven literature is rich and varied, and their songs and poems are famous among other races. Many bards learn their language so they can add Elvish ballads to their repertoires.</languages>
        <action>
            <name>Longbow</name>
            <text>Ranged Weapon Attack: +7 to hit, range 150/600 ft., one target. Hit: 1d8 + 3 piercing damage.</text>
            <attack>|+3|1d8+3</attack>
        </action>
        <action>
            <name>Longsword</name>
            <text>Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 1d8 + 1 slashing damage.</text>
            <attack>|+3|1d8+1</attack>
        </action>
        <action>
            <name>Longsword</name>
            <text>Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 1d8 + 1 slashing damage.</text>
            <attack>|+3|1d8+1</attack>
        </action>
    </pc>
</characters>

**Comment by ceryliae** [comment]
Hi, 

Can you give me some more details on what you're trying to do?

Are you trying to import a character from Fight Club into GM5?

**Comment by ceryliae** [comment]
If I don't get a response by Wednesday I will be closing this.

**Comment by velowebb** [comment]
Yes, a fight club 5 GM formatted file into GM5. 
- Clay

**Comment by ceryliae** [comment]
Can you email me the file and I'll see what I can do. ceryliae@gmail.com

**Comment by velowebb** [comment]
Ive attached the XML for both the FC and the GM.  Both will not import into
either app.

**Comment by ceryliae** [comment]
Will look at this after school. By any chance, do you have the ampersand
(&) anywhere in your character file

**Comment by ceryliae** [comment]
Where did you attach the files?

**Comment by velowebb** [comment]
I'm using the reply from the github email, it must drop the attachments.
- Clay

**Comment by velowebb** [comment]
https://www.dropbox.com/s/yy7g0js5sqkkdqe/felnot-expyortforgm.xml?dl=0
https://www.dropbox.com/s/33odv0lf8m0l2da/felnot-exportforfc.xml?dl=0

**Comment by ceryliae** [comment]
Hi, 

The first link does not work for me.

The second link imports fine for me into FC.

**Comment by ceryliae** [comment]
I was able to get the first link to work. It also imports fine into the GM app. I am not sure what your problem is. Are you trying to import into the compendium?

**Comment by velowebb** [comment]
Yes, where are you supposed to import?
- Clay

**Comment by ceryliae** [comment]
In the DM app you are supposed to enter a campaign, hit the gear in the top
right, and then hit import.

For the player app, go to create a new character, and then select Dropbox.

**Comment by velowebb** [comment]
Awesome, thanks so much. I kept looking for a place in the campaign creation screen, under new PC. 
- Clay

**Comment by ceryliae** [comment]
No problem. Because your issue is solved I will be closing this issue.
