### ISSUE TITLE
Modern Magic warlock

### ISSUE THREAD

**Issue by ghost** [ceryliae/DnDAppFiles#151]
The modern spells were added to the base warlock spells instead of the Ghost in the Machine patron spell list, and the patron is missing from the class
(While the city domain cleric is complete)

**Comment by ghost** [comment]
Correction, the details of the city cleric domain are missing, only the domain spell list was complete.
The patron spell list was still overlooked

**Comment by ceryliae** [comment]
I will take a look at this tomorrow

**Comment by ceryliae** [comment]
Alright, a couple things.

We did not do the class stuff, that's correct. It must have slipped through the cracks. About the warlock spells, there's actually an explanation about that. There was an inconsistency. If you look at the page 5 of the PDF it says, "The following modern themed spells are all suitable for the sorcerer, warlock, or wizard spell lists. Spells marked † are also suitable for the paladin spell list."

I will try to add the class stuff at some point soon.

**Comment by ghost** [comment]
Alright, well except for the "find vehicle", "protection from ballistics", and "commune with city", which were only on the clerics modern magic spell list... all of those spells are just from the warlock GitS patron. So if that was made as a spell list (including the "on/off" cantrip, the spells could be removed from the generic sorcerer/paladin/warlock/wizard/cleric

Just like for the Favored Soul sorcerer bloodline, we could say "if playing in a modern magic campaign, you may choose spells from the Warlock (GitM) spell list, or the city cleric domain"

also i noticed an error on their part of the printing. "synchronicity" is a 4th level spell, but is on the 5th level warlock patron spell list

**Comment by ceryliae** [comment]
Haven't forgotten about this, been busy with the Sword Coast stuff

**Comment by ghost** [comment]
Never mind what I said about removing them from the other class spell lists, one thing though, half the modern spells are missing their (Technomagic) tag, so they can get confused with phb spells at a glance.
Also the non Modern spell's from the city domain disappeared
