### ISSUE TITLE
Oathbreaker Channel

### ISSUE THREAD

**Issue by ghost** [ceryliae/DnDAppFiles#159]
The CD for Oathbreaker paladin currently reads the same as the sacred weapon cd for oath of devotion. It should read:

As an action, the paladin targets one undead creature he or she can see within 30 feet of him or her. The target must make a Wisdom saving throw. On a failed save, the target must obey the paladin's commands for the next 24 hours, or until the paladin uses this Channel Divinity option again. An undead whose challenge rating is equal to or greater than the paladin's level is immune to this effect.

**Comment by ceryliae** [comment]
Hi,

I will get to this during this week. 

Can you try to import the monster manual bestiary or the bestiary compendium? I'm having a crash when I try to import.

**Comment by ghost** [comment]
I imported the bestiary compendium to the player app, and it loaded fine (though now I've got dragons and things that my PCs can't use cluttering my bestiary)

**Comment by ghost** [comment]
This is still wrong in the full compendium

**Comment by ghost** [comment]
I dunno why the issue is closed if it wasn't fixed

**Comment by ceryliae** [comment]
I haven't updated the Dropbox.

**Comment by ceryliae** [comment]
I'm doing it tonight

**Comment by ceryliae** [comment]
I'm doing it tonight

**Comment by ghost** [comment]
Ah, I saw a recent update and that this was recently closed. Thought the two connected
