### ISSUE TITLE
DM screen 1.1.0 typos

### ISSUE THREAD

**Issue by afluffygrue** [ceryliae/DnDAppFiles#16]
Numbering incomplete in Table of Contents expansions

**Comment by ceryliae** [comment]
Can you expand on this?

**Comment by Phied** [comment]
The links without numbers are another category to expand out.  The ones with numbers are a direct link to the content.  Is this the numbering issue you see?

**Comment by afluffygrue** [comment]
Yes! Noob mistake. Thanks.
