### ISSUE TITLE
Unearthed Arcana File

### ISSUE THREAD

**Issue by ceryliae** [ceryliae/DnDAppFiles#162]
With the large number of Unearthed Arcana stuff that we have now, and how it varies from the official stuff, I want to separate the class stuff that comes from the unearthed arcana into a different file.

**Comment by ghost** [comment]
Smart. UA compendium.

(So you can go new storm sorc, or old one with expanded spell list)

**Comment by ghost** [comment]
Smart. UA compendium.

(So you can go new storm sorc, or old one with the "domain" added spells that didn't count towards total spells)

**Comment by ghost** [comment]
Also possibly a tag to the subclasses, or fighting styles, like with the (EE)/(SCAG) tag for spells? That would be EE, SCAG, DMG (for death domain, Oathbreaker, eladrin, and the aasimar) and UA for the stuff they put out to playtest
