### ISSUE TITLE
Legendary/Lair Monster Project

### ISSUE THREAD

**Issue by ceryliae** [ceryliae/DnDAppFiles#181]
This project has two main goals:
1. Monsters with legendary actions are to follow the format used by the monsters from the Out of the Abyss book. The difference in format that I am referring to is an extra entry under legendary actions that has the information on the number of points the monster has for legendary actions. An example of what I am referring to can be seen in the Baphomet entry currently at line 1277 of the Out of the Abyss bestiary file. This needs to be done for all bestiary files except Out of the Abyss.
2. Monsters with lair options are to have a new action created called "Lair Actions", with the entire section transcribed from the book, including any relevant rolls. An example of this can be seen in the Adult Red Dragon entry in the Monster Manual Bestiary, currently located at line 788. If there is a CR increase while a monster is in its lair, please make a note of this with the following format, "While in its lair, this monster's CR increases to X".

**Comment by ghost** [comment]
Yeah, I noticed a few monsters have the relevant number of legendary actions per round they posses, but most monsters with the list of actions are missing the number they can take

**Comment by ghost** [comment]
The pit fiend is still missing all of its actions following its innate spell casting
