### ISSUE TITLE
Pit fiend

### ISSUE THREAD

**Issue by ghost** [ceryliae/DnDAppFiles#182]
Everything following innate spell casting is missing. It doesn't show any of its actions/attacks

**Comment by ghost** [comment]
Okay it is worse than I thought, I don't know how many so I would check them all

Monsters seem to be entirely missing all of their weapon/natural attacks. A CR2 spines devil is missing it, same as the CR 20 pit fiend.

I think every last monster needs to be checked :-/

**Comment by ceryliae** [comment]
Could you make a list?

**Comment by ghost** [comment]
There are 560 monsters, it seems NOT uncommon. at least 1 of every 10 when I do a random spot check. I'm not sure I have the patience to go through them all, note them down, and report back here.

But it also seems like it ties in with monsters missing their # of lair actions / round, spell casting, features, or now actions/attacks.
