### ISSUE TITLE
DM screen

### ISSUE THREAD

**Issue by ghost** [ceryliae/DnDAppFiles#184]
I deleted all loaded files to upload them again since there's been organizational changes. But now the DM screen keeps having the same error
Error 65
Line 1 Column 50

**Comment by ceryliae** [comment]
Are you importing in the correct place? Inside a campaign, tap on the DM
screen icon and import there.

**Comment by erictelam** [comment]
Yes I did and have the same issue

**Comment by ceryliae** [comment]
I just tried to recreate the issue that you two are having, but I was able to import the DM screen just fine. Could you take a screenshot of the error you're getting please?

**Comment by erictelam** [comment]
Same results on iPad

**Comment by ceryliae** [comment]
Can I get a screenshot?

**Comment by erictelam** [comment]
I attached them don't know why they didn't send.  I'll try again.

**Comment by ceryliae** [comment]
Doesn't work that way. You have to upload them somewhere. Or send them to
me at ceryliae@gmail.com

**Comment by erictelam** [comment]
Just did both.

**Comment by ceryliae** [comment]
I responded to your email

**Comment by erictelam** [comment]
Yes problem is solved. Must upload from in campaign IN DM screen. It has its own upload button. I did not see that before. 

Thanks

**Comment by ghost** [comment]
Oh, I didn't have any campaigns.
That's a really weird way to have to do it :-/
