### ISSUE TITLE
Add item rarity information?

### ISSUE THREAD

**Issue by DesktopMan** [ceryliae/DnDAppFiles#194]
Are there any plans to add item rarity information? It would be very useful for generating loot or quickly calculating prices.

**Comment by stevenjonescgm** [comment]
@vagueGM started this with https://github.com/vagueGM/DnDAppFiles/commit/e442d5ef191db782d8d074e36e901a01f98752e2 which is on top of some other typo fixes

I haven't looked at or tested that commit yet.
