### ISSUE TITLE
Any suggestions on how to format information originally presented as a table?

### ISSUE THREAD

**Issue by theundecided** [ceryliae/DnDAppFiles#216]
im trying to figure out how to input information originaly presented in a table. I dont think Ive seen much information in app presented in a table though. 

thought? 

---

| Firearm​ | Cost​ | Damage | ​ Weight | Range​ | Properties |
| :-: | :-: | :-: | :-: | :-: | :-: |
| Pistol | ​​250g​ | 1d10 piercing​ | 3 lbs​ | (100/400)​ | Reload 4, Misfire 1 |
| Musket | ​​500g​ | 1d12 piercing​ | 10 lbs | (200/800) | ​Two-handed, Reload 1, Misfire 2 |
| Pepperbox​ | 450g​ | 1d10 piercing​ | 4 lbs | ​(150/600)​ | Reload 6, Misfire 2 |
| Scattergun | ​500g​ | 1d8 piercing ​ | 10 lbs​ | (15/30)​ | Two-Handed, Reload 2, Misfire 3, Scatter |
| Bad News​ | (Crafted) | 2d12 piercing​ | 25 lbs​ | (300/1200) | ​Two-handed, Reload 1, Misfire 3 |
| Hand Cannon | ​(Crafted) | 2d8 fire​​ | 4 lbs​ | (30/60)​ | Reload 1, Misfire 3, Explosive​ |

**Comment by ceryliae** [comment]
This is a rather large table. We've done stuff like:

A | B | C
1 - A | B | C

But it might be better if you use bullet points.

Pistol:
Cost - 200 gp
Damage - 1d10

Etc.

**Comment by NeilMartin** [comment]
Are you asking how to add just these 6 items to the XML or how to add table data instead of XML?

The above looks like Percy's items from Critical Role. I'd add them as items to some homebrew item.xml like this...

```
<item>
    <name>Bad News</name>
    <type>R</type>
    <value>crafted</value>
    <weight>25</weight>
    <dmg2>2d12</dmg2>
    <dmgType>P</dmgType>
    <property>A,H,2H</property>
    <range>300/1200</range>
    <text>Ammunition: You can use a weapon that has the ammunition property to make a ranged attack only if you have ammunition to fire from the weapon. Each time you attack with the weapon, you expend one piece of ammunition. Drawing the ammunition from a quiver, case, or other container is part of the attack. </text>
    <text />
    <text>If you use a weapon that has the ammunition property to make a melee attack, you treat the weapon as an improvised weapon (see "Improvised Weapons" later in the section). A sling must be loaded to deal any damage when used in this way.</text>
    <text />
    <text>Heavy: Small creatures have disadvantage on attack rolls with heavy weapons. A heavy weapon's size and bulk make it too large for a Small creature to use effectively.</text>
    <text />
    <text>Range: A weapon that can be used to make a ranged attack has a range shown in parentheses after the ammunition or thrown property. The range lists two numbers. The first is the weapon's normal range in feet, and the second indicates the weapon's maximum range. When attacking a target beyond normal range, you have disadvantage on the attack roll. You can't attack a target beyond the weapon's long range.</text>
    <text />
    <text>Two-Handed: This weapon requires two hands to use.</text>
    <text />
    <text>Reload 1, Misfire 3</text>
    <text />
    <text>Source: Matt Mercer</text>
</item>
```

**Comment by theundecided** [comment]
well.....I WAS asking how to format as a table....but your solution I think works better then [what I came up with](https://github.com/theundecided/DnDAppFiles/blob/master/Homebrew/Fighter-gunslinger.unfinished.xml) . 

I forgot that they technicly are items too.....perhaps they dont actualy need to be in the _class_ area ?

**Comment by theundecided** [comment]
I like the idea of removing this table from the class and adding the firearms as items. thanks
