### ISSUE TITLE
Proposal: Re-organize / (re-)structure (for future additions) the "Homebrew" folder

### ISSUE THREAD

**Issue by theundecided** [ceryliae/DnDAppFiles#219]
I propose we add sub folders similar to how dandwiki structures stuff. for example:
- Class
- Races
- Backgrounds
- Equipment
- Spells
- Character Options
  - Class Archetypes
  - Feats
  - Skills 
  - Race Variants 
  - Class Feature Variants

thoughts?

**Comment by ceryliae** [comment]
I like it

**Comment by theundecided** [comment]
the only complication with this plan is how to go about including homebrew spells, and items. 

should we have individual files per "homebrew" or have a colective "homebrew spells" file. 

when say a archetype contains items I would just include a items.xml file next to the class.xml file....

**Comment by NeilMartin** [comment]
I would prefer the directory names to be the source and the file names to be the content. So the users can select which content they want included by selecting the directory names. e.g.

MonsterManual/monsters.xml
HoardOfTheDragonQueen/monsters.xml
HoardOfTheDragonQueen/items.xml
SRD/monsters.xml
SRD/items.xml
SRD/classes.xml
SRD/spells.xml
PHB/spells.xml
UsersOwnHomeBrew/items.xml
UsersOwnHomeBrew/feats.xml
MattMercer/items.xml

Then the app could scan the directory names and provide checkboxes for the user to filter. The app would collate/union all of the selected items.xml for the chosen directories.

**Comment by theundecided** [comment]
if im not mistaken all of MM, HOTD, SRD, PHB wouldn't technically classify as "homebrews" and I believe  are already in the master xml.  if your suggesting a total re-structuring of _everything_  I would agree. 

however what Im primarily thinking of is just pertaining of homebrews exclusively. from a LARGE variety of different locations. (some perhaps only slightly different from others).

that being said....I like where your coming from. ....

**Comment by ghost** [comment]
There seems to be issues with the files for the Blood Hunter class and Gunslinger archetype, I am getting errors when I try to import the new files

**Comment by theundecided** [comment]
drat....ill see whats going on when I get a moment....(at least with my gunslinger addition)
- [ ] troubleshoot gunslinger

**Comment by LogosWorks** [comment]
Why would the class and race not be under character options?

- Equipment
- Spells
- Character Options
  - Class
        - Class Archetypes
  - Races
  - Backgrounds
   - Feats
   - Skills
- Race Variants
- Class Feature Variants
