### ISSUE TITLE
Thoughts on linking to users

### ISSUE THREAD

**Issue by camdenb** [ceryliae/DnDAppFiles#220]
Hey! 

I'm working on a D&D webapp and I'd like to import the contents of these files and display them on the site -- however, knowing WOTC, they'd issue a DMCA takedown in short order if I do that. So as a legal workaround (similar to what Lion's Den does), I'd like to link my users to either this repo or the Google forms link (in the readme). I'm wondering what your thoughts are on this.

Thanks!

**Comment by rbhaddon** [comment]
Is that still true?  I've been hearing about some kind of open RPG initiative that WoTC is involved with.

**Comment by ghost** [comment]
http://dnd.wizards.com/articles/features/systems-reference-document-srd

**Comment by camdenb** [comment]
Oh, wow! Thanks for the info - this is huge!

**Comment by ghost** [comment]
Happy to help. :)

**Comment by NeilMartin** [comment]
That license doesn't allow you to publish their content, but allows you to
create new content that uses 5E rules and Forgotten Realms setting e.g. a
new campaign.

On 22 June 2016 at 16:25, cpekruhn notifications@github.com wrote:

> Happy to help. :)
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/ceryliae/DnDAppFiles/issues/220#issuecomment-227907011,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABDJrgM7gY6-u43zowOS-FL14NryhRptks5qOcRTgaJpZM4I8TEy
> .

## 

neil_martin_vanpubs http://www.vanpubs.com

**Comment by ghost** [comment]
Basically, he can publish the content in the SRD using the OGL. Lion's Den added this info in its apps following the release of the OGL earlier this year.

**Comment by NeilMartin** [comment]
That's cool.

On 22 June 2016 at 16:32, cpekruhn notifications@github.com wrote:

> Basically, he can publish the content in the SRD using the OGL. Lion's Den
> added this info in its apps following the release of the OGL earlier this
> year.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/ceryliae/DnDAppFiles/issues/220#issuecomment-227908166,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABDJrqx13gIixaz7Cd7GMIGa877unL3xks5qOcYGgaJpZM4I8TEy
> .

## 

neil_martin_vanpubs http://www.vanpubs.com

**Comment by LogosWorks** [comment]
@camdenb 
I was wanting to create a Mac app that can make use of these files. I am not that good of a programer yet, but am learning. I wanted to add a little more of a focus on the compendium (better search and filters) and drag and drop character (npc) creation. along with using math and dmg to auto level all the bestiary monsters to any (reasonable CR deemed needed on button not totally auto...)  Perhaps I could help you in some way?

**Comment by ceryliae** [comment]
https://github.com/ceryliae/DnDAppFiles/wiki/Using-these-files
