### ISSUE TITLE
Homebrew crash

### ISSUE THREAD

**Issue by ghost** [ceryliae/DnDAppFiles#222]
There seems to be issues with the files for the Blood Hunter class and Gunslinger archetype, I am getting errors when I try to import the new files

The gunslinger items also have shared names with items from the Renaissance items, and if they have different stats, should be named differently

**Comment by ghost** [comment]
Seconded, as of a month later. Specifically having an issues importing into the latest version of the iPad application, whatever it's worth.

**Comment by ceryliae** [comment]
They should both be fixed. Sorry it took so long. They'll be put on the Dropbox when I get the storm king files up.

**Comment by ghost** [comment]
One of the things I did notice was that when fixed (I pulled the code into a local XML for a test) that it adds a new class called Fighter with no abilities except the gunslinger ones at certain levels. Can it be worked to collapse into the main Fighter class?

**Comment by ceryliae** [comment]
No, the app does not have that capability, and I'm not willing to keep two files maintained every time I make a change to the master class file, sorry.

**Comment by ghost** [comment]
Well then, a blank fighter with just the gunslinger abilities and none of the fighter abilities is useless. Clone over the fighter stuff and just rename the whole class as Fighter-Gunslinger?

**Comment by ceryliae** [comment]
To be quite honest with you, I don't really have interest maintaining the Homebrew stuff. Someone else submitted a pull request with that stuff, and I just added it to the Dropbox. The official 5e stuff keeps me busy enough and I have other projects as well as a busy life. 

If I have time, I'll try to get around to doing this but I don't really see it happening anytime soon.

**Comment by ghost** [comment]
Still getting errors on the blood Hunter when I try to import it.
"Unable to parse file. Please verify that your file format is valid. Error 65, Line: 1, Column: 50"

**Comment by ceryliae** [comment]
Are you using the files on the Dropbox?

**Comment by ghost** [comment]
Oh, right, they haven't been changed yet, sorry

**Comment by ghost** [comment]
Yes

**Comment by ceryliae** [comment]
You can grab them from here if you want them now. By the end of the month
I'll have them along with the storm kings stuff on the Dropbox

**Comment by ghost** [comment]
Ah I see. I cant do it right on my phone. It opens the webpage in safari, then when I tried to save it to Dropbox to import to the app, it saved as a pdf

**Comment by ceryliae** [comment]
You'll have to use your computer to download it and upload to Dropbox

**Comment by ghost** [comment]
I'll just wait, sorry for the disruption
