### ISSUE TITLE
DM Screen 1.5.2.html won't Import

### ISSUE THREAD

**Issue by ghost** [ceryliae/DnDAppFiles#228]
The exact error I get is:

> **Unable to parse file. Please verify that your file format is valid. Error 65, Line: 1, Column: 50**

**Comment by ceryliae** [comment]
You're not parsing it in the right location. Please check the FAQ, and then come back here if you still have questions.

**Comment by ghost** [comment]
Oh duh, sorry. I thought that was the rules compendium for the GM App. I'm an idiot.
