### ISSUE TITLE
Kobold's Press Tome of Beasts

### ISSUE THREAD

**Issue by tonymccallie** [ceryliae/DnDAppFiles#236]
Is there any plan to add this or is there any way I can help add these when I get the book?

**Comment by neswii** [comment]
I asked him the same some weeks ago and never got a response. I did the first monster myself, since I own the book and the little carton figurines, but it's a LOT of work. Definitely would need the help of a lot of people to complete it in a couple of months.

**Comment by ceryliae** [comment]
I don't have any plans to do any content that's not official Wizards of the Coast material. Sorry for the delayed response.

**Comment by nonplayer** [comment]
This has been closed for a while, but I figured I'd chime in. I extracted the text from the Tome of Beasts this evening, and am curious if there's still any interest in having the monsters added to the bestiary. There's a LOT of text to convert, though, and my XML scripting skills are pretty minimal.

If any fellow owners of the book are up for assisting, or have already started on this project, let's chat.

**Comment by ceryliae** [comment]
I've had requests for third party supplements from time to time, including Tome of Beasts. I'm sure that there is some level of interest, but the interest in official stuff obviously is larger. I've been thinking about making a poll on my Patreon listing several third party supplements and then adding the one with the most votes, but that's still a ways off.

**Comment by snaggle2th** [comment]
You have a Patreon listing?  Is this something that you have promoted here?  I would definitely make a contribution!  And I would definitely contribute to get TOB done!  

That said, if you don't have immediate plans, and don't consider it an integral part of your Patreon strategy, do you have any objections to us starting it here?  If so, where would the appropriate place be?  Possibly a new 'Third Party' folder?

@nonplayer, @neswii, @tonymccallie Is there a way we could split the work up to make it more manageable?  I am wondering if we could start with an individual file for each letter.  Let me know what you guys think.

**Comment by ghost** [comment]
Me too. I´d like to contribute to your patreon account.


Zander Catta Preta

2017-02-10 12:38 GMT-02:00 snaggle2th <notifications@github.com>:

**Comment by ceryliae** [comment]
@snaggle2th The Patreon isn't something I've actively promoted here on Github. I've only promoted it on my website (www.5edmscreen.com) and the Dropbox group. You're welcome to join it though, it would be greatly appreciated. I don't consider it to be an integral part of my Patreon strategy, and I definitely don't have a problem with anyone starting work on here. 

Anyone interested in my Patreon can go to https://www.patreon.com/5edmscreen

**Comment by nonplayer** [comment]
@ceryliae would you mind re-opening this issue?

Or should we start a new one? Or would you rather we start it elsewhere?

**Comment by nonplayer** [comment]
@tonymccallie @neswii @snaggle2th 

I've extracted the text and begun the long process of cleaning it up in plain text format. Might take a couple of days as I find time for it. I've only ever used git for personal projects and not full team collaboration (taught myself how to do pull requests just yesterday in order to update files for this very app, hah!), but am slowly figuring it out. Where should I put the text?

**Comment by Vicorin** [comment]
I don't really have much xml experience, but looking at the tutorial in the app, it doesn't look terribly difficult. If you need some extra manpower, I'd be more than happy to do what I can.

**Comment by snaggle2th** [comment]
@nonplayer, that's awesome that you have extracted the text already!  Can I suggest that we go with the path, to stick with the current naming conventions:  /Third Party/Kobold/Bestiary/Tome of Beasts.xml.  To facilitate splitting up the work, we can create the folder /Third Party/Kobold/Bestiary/Tome of Beasts/, and working files, including the text file, can reside there.  @nonplayer, once you have the text ready, perhaps you can post it there?   If I get a chance before then, I may post y.xml there, with a formatted monster or two.  Then folks can use that for a template to start other letters.

@ceryliae, can you (or anybody else) suggest a monster that has all the bells and whistles (spells, lair/legendary actions, etc.), and would therefore make a good candidate for reverse-engineering?  Also, any feedback on that path?  Let us know.

**Comment by ceryliae** [comment]
I like the path. As for a monster with all the bells and whistles, the
tarrasque isn't a bad choice.

**Comment by nonplayer** [comment]
@snaggle2th Okay! I'm hoping to find time for it this week. I've got all the text, looks good, just gota fix thirty-two thousands lines of funky line breaks. I'm about 3/8 of the way done.

**Comment by nonplayer** [comment]
I reached a rough midpoint, and figured I'd share the work done so far. Due to the way I'm editing the text, I started from the end and am working backward. Here is the raw text of letters L-Z.
[Tome of Beasts raw text L-Z.txt](https://github.com/ceryliae/DnDAppFiles/files/785377/Tome.of.Beasts.raw.text.L-Z.txt)

**Comment by Digital-Hippie** [comment]
@nonplayer Its got a couple of bugs (some of the monsters with unusually formatted tables etc.) but I put together a matlab script to parse that raw text and spit out an XML. If you post A-K here I'll go ahead and convert that as well. I'll also share a complete compendium once I have both halves done and bug free. Thanks for doing the text scan, I've been meaning to do this for awhile.
[TomeofBeastsL-Zdraft.xml.zip](https://github.com/ceryliae/DnDAppFiles/files/789307/TomeofBeastsL-Zdraft.xml.zip)

**Comment by nonplayer** [comment]
Here's F-K. I thought I would get more done but those damn Fey Lords kicked my butt. All those Lair Actions and Regional Effects! I suspect the Demon and Devil lords will drive me mad (fitting, right?) The whole D section looks particularly intimidating...
[Tome of Beasts raw text F-K.txt](https://github.com/ceryliae/DnDAppFiles/files/798357/Tome.of.Beasts.raw.text.F-K.txt)

**Comment by nonplayer** [comment]
Oh god, I've reached the Dragons. SO MUCH EDITING

**Comment by Digital-Hippie** [comment]
I'm definitely not looking forward to letter D. Demons, Devils, and Dragons. I've finished up F-K and think I caught all the bugs and weird formatting (those Fey Lords and Ladies man...). As far as I can tell most of these come out on the Game Master 5 app exactly how they are in the book. For some reason a few (like the Bear King) come out a bit off in the Fight Club 5 app. I don't think that app parses parentheses as well. In either case, this batch is done and i'm almost done debugging L-Z as well. I'll post a complete document once we have them all done. Cheers.
[TomeofBeastsF-K.zip](https://github.com/ceryliae/DnDAppFiles/files/805855/TomeofBeastsF-K.zip)

**Comment by Digital-Hippie** [comment]
Okay, All done with F-Z and I think they're all debugged now. I'm sure I missed a few things but here is everything I've got so far.
[TomeofBeastsF-Z.zip](https://github.com/ceryliae/DnDAppFiles/files/809871/TomeofBeastsF-Z.zip)

**Comment by Papershardz** [comment]
@Digital-Hippie Thank's a bunch for doing this, can't wait to put this into the app.

**Comment by nonplayer** [comment]
Getting close to complete, I promise. I wish I could automate it a bit more, but the hodgepodge nature of the text extraction makes it very difficult, each creature needs to be hand-edited and rearranged.

**Comment by Snazzywizard571** [comment]
If you need any help on the last bit i can finish it up tonight. Just let me know where you left off.

**Comment by nonplayer** [comment]
Creatures A-E, complete!

[Tome of Beasts raw text A-E.txt](https://github.com/ceryliae/DnDAppFiles/files/817333/Tome.of.Beasts.raw.text.A-E.txt)

**Comment by Digital-Hippie** [comment]
Excellent! Here's the rough xml. I'm sure its got plenty of bugs but I'll get to work on those now and probably have to totally complete compendium up in a day or so. Almost there! 
[TomeofBeastsA-Edraft.zip](https://github.com/ceryliae/DnDAppFiles/files/817435/TomeofBeastsA-Edraft.zip)

**Comment by nonplayer** [comment]
AH I totally spaced! Here are the extra enemies from the Appendix, as well.
[Tome of Beasts APPENDIX A raw text.txt](https://github.com/ceryliae/DnDAppFiles/files/818973/Tome.of.Beasts.APPENDIX.A.raw.text.txt)

**Comment by Digital-Hippie** [comment]
Okay! That took longer than I thought! Here is A-Z (everything but the Appendix enemies) as debugged as can be with only one set of eyes. I'll do the appendix lot soon and then reshare a really complete compendium.
[TomeofBeastsA-Z.zip](https://github.com/ceryliae/DnDAppFiles/files/823535/TomeofBeastsA-Z.zip)

**Comment by Digital-Hippie** [comment]
All done! The villain codex is added on at the end. Feel free to share these within the DnDAppFiles folder if you'd like as well. Enjoy!
[Tome of Beasts.zip](https://github.com/ceryliae/DnDAppFiles/files/836141/Tome.of.Beasts.zip)

**Comment by ceryliae** [comment]
Wow @Digital-Hippie thanks so much for your contribution. I'm going to be putting out a dropbox update tomorrow, and I will be including this in it. I will mention everyone who helped out with this project. Thanks everyone!

**Comment by nonplayer** [comment]
@ceryliae just to confirm, what is the latest filestamp on the dropbox data? I want to make sure mine's up to date with the latest changes. Is Jan 18th 2017 the last modified date?

**Comment by ceryliae** [comment]
I'm bringing the Dropbox up to date today.
