### ISSUE TITLE
Yuan-ti or Yuan_ti

### ISSUE THREAD

**Issue by ammulder** [ceryliae/DnDAppFiles#241]
The Yuan-ti text in the Monster Manual Bestiary.xml has a number of occurrences of yuan_ti and Yuan_ti (with an underscore instead of a hyphen).  I assume that's not intentional?

**Comment by ceryliae** [comment]
No, not intentional. That was probably an error from way back when because I used OCR to speed up data entry. Are you planning on fixing it or do you want me to add it to my to-do list?

**Comment by ammulder** [comment]
How would I go about fixing it?  (I just did a search and replace in my local copy...)
