### ISSUE TITLE
Potion of Speed Error in Item Compendium

### ISSUE THREAD

**Issue by mgstreak** [ceryliae/DnDAppFiles#251]
In the Item Compendium, the Potion of Speed currently has the description of the Potion of Acid Resistance. It's description should read:

"When you drink this potion, you gain the effect of the haste spell for 1 minute (no concentration required). The potion's yellow fluid is streaked with black and swirls on its own."

(Am I able to attempt these edits myself, where necessary, here in GitHub, subject to someone's approval?)

**Comment by ceryliae** [comment]
Is this error in magic items.xml as well?

Yes, you're able to submit a pull request with changes pending my approval.

**Comment by mgstreak** [comment]
Yes, it's incorrect in both. (Forgive me... I've never used GitHub before. I'll try to learn how!(

**Comment by mgstreak** [comment]
I'm not sure how to go about making a correction to the Items Compendium. Sorry.
