### ISSUE TITLE
No spell lists for new UA classes/archetypes

### ISSUE THREAD

**Issue by Vicorin** [ceryliae/DnDAppFiles#257]
You added the Unearthed Arcana options they've been putting out, which I really appreciate. However, there's no Artificer spell list, and there's no spell lists for the different archetypes. I don't know if this was intentional or not, and it's a relatively small bit of work on my part to add them myself, but I still thought I'd bring this to your attention.

**Comment by ceryliae** [comment]
This is unintentional. I will add it in the next update
