### ISSUE TITLE
No way to export adventures from Game Master 5 or to duplicate them within the app

### ISSUE THREAD

**Issue by ArcticStagMedia** [ceryliae/DnDAppFiles#273]

**Comment by nonplayer** [comment]
I don't believe this is the right place for that kind of issue. This project doesn't design the app itself. Have you contacted the app developer?

**Comment by ArcticStagMedia** [comment]
Pretty sure this is not the correct location but as the developer doesn't have standard means of contact (ie Facebook, website) I put it somewhere where I thought the debs might see it

**Comment by Gibbothicus** [comment]
Lions Den has no affiliation with this data as to avoid a DMCA takedown by WotC. Here is their email lionsden.contact@gmail.com

**Comment by ArcticStagMedia** [comment]
Thank you!
