### ISSUE TITLE
Arcane trickster spells 

### ISSUE THREAD

**Issue by ceryliae** [ceryliae/DnDAppFiles#55]
I asked Cuag if he would work on it since spells are his thing. I have not gotten a response yet. I will update with response. I don't want anyone else to work on this, the spells are his thing.

**Comment by Phied** [comment]
No problem.  Can you be sure to have him add this tag to the spells?  <roll></roll>  He can put things like 1d6 or 2d8 or whatever the spell damage is.  This isn't in the last update notes, but it does add things to the spell to be able to roll damage.

**Comment by Phied** [comment]
AH it took out the tag!  < roll> and < /roll> is what needs to be added.
