### ISSUE TITLE
Unearthed arcana classes

### ISSUE THREAD

**Issue by ceryliae** [ceryliae/DnDAppFiles#61]
Although it would be ideal to do these classes if/when we ever get subclass support in the app, but we need to have them. 

There's the sorcerer subclass which shouldn't be that big of a problem, but the ranger isn't actually a 
new subclass, it's a new base class. So we will need to create two new classes for the ranger, Spell-less Ranger (Hunter) and (Beastmaster)
- [ ] Spell-less Ranger (Hunter)
- [ ] Spell-less Ranger (Beastmaster)
- [ ] Favored Soul Sorcerer

**Comment by ghost** [comment]
You mean the Favored Soul?

**Comment by ceryliae** [comment]
Yes
