### ISSUE TITLE
Class To Do List

### ISSUE THREAD

**Issue by ceryliae** [ceryliae/DnDAppFiles#98]
## From [Unearthed Arcana - Modifying Classes](http://media.wizards.com/2015/downloads/dnd/UA3_ClassDesignVariants.pdf)
- [ ] Favored Soul Sorcerer
- [ ] Spell-less ranger (hunter)
- [ ] Spell-less ranger (beastmaster)
## From [Unearthed Arcana - Waterborne Adventures](http://media.wizards.com/2015/downloads/dnd/UA_Waterborne_v3.pdf)
- [x] Storm Sorcerer
- [x] Swashbuckler Rogue
- [x] Add Fighting Style: Mariner to Paladin, Fighter, and Ranger.
## Miscellaneous
- [ ] Finish Warlock class, it is still the raw text.

**Comment by ghost** [comment]
There's a missing feature at level 6 for the storm sorcerer. There is two, and one is more fluff, controlling the wind. That's the one included, but there's another one that does burst damage when you cast a spell of certain type

**Comment by afluffygrue** [comment]
Sorcerer-Storm-Heart of the Storm added

**Comment by ghost** [comment]
Thanks :D
